#!/bin/bash

userscripts_dir="/home/jonathan/.config/sxmo/userscripts"
myscripts_dir="/home/jonathan/Documents/myscripts"

if [ -d "$userscripts_dir" ]; then
  ### Take action if $DIR exists ###
  echo " $userscripts_dir exists"
else
  ###  Control will jump here if $DIR does NOT exists ###
  mkdir -p $userscripts_dir
fi

cd $myscripts_dir

cp -r userscripts/* $userscripts_dir


