#!/usr/bin/sh

#source ../bash-scripts/config.sh

sh /home/alarm/Documents/phone/bash-scripts/feh-change-background.sh &

telegram-desktop 

#firefox -profile "/home/$user_pine/Documents/phone/firefox-profiles/fb-personal" https://web.telegram.org 

