#!/bin/sh

sh /home/alarm/Documents/phone/bash-scripts/feh-change-background.sh &

xfce4-terminal --command='bash -l -c "yay && sleep 10s"' 

#xfce4-terminal --zoom=4 --command='ash -l -c "sudo apk update && sudo apk upgrade && sudo flatpak upgrade && sleep 5s"'
