#!/usr/bin/sh

source ../bash-scripts/config.sh

sh /home/$user_pine/Documents/phone/bash-scripts/feh-change-background.sh &

firefox -profile "/home/$user_pine/Documents/phone/firefox-profiles/fb-personal" https://web.telegram.org 


