#!/bin/sh

sh /home/jonathan/Documents/phone/bash-scripts/feh-change-background.sh &

#telegram-desktop

firefox -profile "/home/jonathan/Documents/phone/firefox-profiles/reddit" -new-window web.telegram.org 
