// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "abfefe2b-5013-46fb-b72a-247693f635ae");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1609851478);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1610265923);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1610266044);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1610521475);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1610266164);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1610266285);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1609851148);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1609851598);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 41294);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1609842168);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8bf46e16-c9bc-4846-93f4-e559569ae18d}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1610521478023");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1610543078023");
user_pref("browser.search.region", "PH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210106181555");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1609858604");
user_pref("browser.slowStartup.averageTime", 12477);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20210106181555");
user_pref("browser.startup.homepage_override.mstone", "78.6.1");
user_pref("browser.startup.lastColdStartupCheck", 1610521470);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "78.6.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "eb0eda9676174e63b288d67f2016b550");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1609851478);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210106181555");
user_pref("extensions.lastAppVersion", "78.6.1");
user_pref("extensions.lastPlatformVersion", "78.6.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"be277753-f82c-4054-94d8-58e5c4716f85\",\"formautofill@mozilla.org\":\"55016e51-390e-4a32-b3a9-66ae45e29b72\",\"screenshots@mozilla.org\":\"669c4ac0-bfc6-4363-9d7d-e33431e81197\",\"webcompat-reporter@mozilla.org\":\"f503fc04-ee54-4fd3-873b-c831917a285a\",\"webcompat@mozilla.org\":\"a0eac6ac-830a-4c67-a000-27bf7863682b\",\"default-theme@mozilla.org\":\"ca2c2d52-e702-467f-b34f-02771fed2410\",\"google@search.mozilla.org\":\"5b1e126e-04f8-4df1-aeb5-fa7150de5e48\",\"amazondotcom@search.mozilla.org\":\"91c85841-7148-45ff-84d7-da671df78d44\",\"wikipedia@search.mozilla.org\":\"824c5277-2047-4fc9-94bf-e705d4e62bdf\",\"bing@search.mozilla.org\":\"fc62812c-01e3-4a64-a174-aa3154e20696\",\"ddg@search.mozilla.org\":\"abce040b-c411-4ed0-99ab-2c68dbeb3f11\"}");
user_pref("idle.lastDailyNotification", 1610266106);
user_pref("media.gmp-manager.buildID", "20210106181555");
user_pref("media.gmp-manager.lastCheck", 1610265945);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1609851274);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1609851114);
user_pref("security.remote_settings.intermediates.checked", 1609851114);
user_pref("services.blocklist.addons-mlbf.checked", 1610522344);
user_pref("services.blocklist.gfx.checked", 1610522344);
user_pref("services.blocklist.pinning.checked", 1610265930);
user_pref("services.blocklist.plugins.checked", 1610522344);
user_pref("services.settings.clock_skew_seconds", -867);
user_pref("services.settings.last_etag", "\"1610479990643\"");
user_pref("services.settings.last_update_seconds", 1610522344);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1610522344);
user_pref("services.settings.main.cfr-fxa.last_check", 1610522344);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1610522344);
user_pref("services.settings.main.hijack-blocklists.last_check", 1610522344);
user_pref("services.settings.main.language-dictionaries.last_check", 1610522344);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1610522344);
user_pref("services.settings.main.public-suffix-list.last_check", 1610522344);
user_pref("services.settings.main.search-config.last_check", 1610522344);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1610522344);
user_pref("services.settings.main.sites-classification.last_check", 1610522344);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1610522344);
user_pref("services.settings.main.whats-new-panel.last_check", 1610522344);
user_pref("services.settings.security.onecrl.checked", 1610265930);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1609851274);
user_pref("toolkit.startup.last_success", 1610521462);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210106181555");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
