// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "113d1748-32a8-4ad4-b817-fe9d90f53bb5");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1609486033);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1609548736);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1609548908);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1609549155);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1609549007);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1609485913);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1609485823);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1609486154);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 73675);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1609485706);
user_pref("browser.laterrun.bookkeeping.sessionCount", 11);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2a019a16-01f3-43ba-baa1-022f7cd8c17e}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1609548715469");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1609570315469");
user_pref("browser.search.region", "PH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20201222151322");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1609549155");
user_pref("browser.slowStartup.averageTime", 3780);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20201222151322");
user_pref("browser.startup.homepage_override.mstone", "78.6.0");
user_pref("browser.startup.lastColdStartupCheck", 1609549149);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "78.6.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "e9b8486d336341dbb85fadb88117b9f5");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1609486034);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20201222151322");
user_pref("extensions.lastAppVersion", "78.6.0");
user_pref("extensions.lastPlatformVersion", "78.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"2575751a-daed-4148-b6fa-8ff937d1c820\",\"formautofill@mozilla.org\":\"6ac62e5c-57e8-4c8c-a7bf-02eb1a1541b2\",\"screenshots@mozilla.org\":\"93bcd14b-99b0-4273-98d1-6cc06462c5f3\",\"webcompat-reporter@mozilla.org\":\"0535bcde-2322-4b25-a3f8-dbdecb6614eb\",\"webcompat@mozilla.org\":\"9ec6dcb8-0348-4127-9f01-8e7d98d8fc5e\",\"default-theme@mozilla.org\":\"c4d862b2-45a5-45c6-8fd2-ca4c4449055d\",\"google@search.mozilla.org\":\"7145ecac-27b7-4acd-a1a9-9f9fa0256776\",\"amazondotcom@search.mozilla.org\":\"c608f400-4031-425d-a0fb-01fff6ee89f2\",\"wikipedia@search.mozilla.org\":\"5c5dc610-b740-44d7-9ee7-3cf6fe9fd531\",\"bing@search.mozilla.org\":\"aa18b568-9049-4972-affb-7970e416d908\",\"ddg@search.mozilla.org\":\"ad958970-3b06-4168-bad4-7c49477bb6b5\"}");
user_pref("font.size.variable.x-western", 17);
user_pref("general.useragent.override", "Firefox/78.0");
user_pref("media.gmp-manager.buildID", "20201222151322");
user_pref("media.gmp-manager.lastCheck", 1609485927);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.blocklist.addons-mlbf.checked", 1609548716);
user_pref("services.blocklist.gfx.checked", 1609548716);
user_pref("services.blocklist.plugins.checked", 1609548716);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1609545680251\"");
user_pref("services.settings.last_update_seconds", 1609548716);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1609548716);
user_pref("services.settings.main.cfr-fxa.last_check", 1609548716);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1609548716);
user_pref("services.settings.main.hijack-blocklists.last_check", 1609548716);
user_pref("services.settings.main.language-dictionaries.last_check", 1609548716);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1609548716);
user_pref("services.settings.main.search-config.last_check", 1609548716);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1609548716);
user_pref("services.settings.main.sites-classification.last_check", 1609548716);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1609548716);
user_pref("services.settings.main.whats-new-panel.last_check", 1609548716);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1609549145);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20201222151322");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
