// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "b64aa5ba-a690-42b2-8368-880a8afce999");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1610106309);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1610106069);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1610106286);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1610106437);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1610012878);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1610106189);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1609858630);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1610106455);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 44488);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.lastDir", "/home/jonathan/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1609858569);
user_pref("browser.laterrun.bookkeeping.sessionCount", 9);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{84f3cf64-4698-47a3-bdfe-388dde5b542d}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1610106050194");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1610127650194");
user_pref("browser.search.region", "PH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210106181555");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1610012864");
user_pref("browser.slowStartup.averageTime", 9229);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20210106181555");
user_pref("browser.startup.homepage_override.mstone", "78.6.1");
user_pref("browser.startup.lastColdStartupCheck", 1610106427);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "78.6.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "3e2e69dc3c69493ea0f1bf342274c14a");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1610106311);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210106181555");
user_pref("extensions.lastAppVersion", "78.6.1");
user_pref("extensions.lastPlatformVersion", "78.6.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4f076ae3-0778-4ffa-a5c3-ac5d69487025\",\"formautofill@mozilla.org\":\"f3c89902-21e6-4fdc-8f4e-5ec93371c755\",\"screenshots@mozilla.org\":\"c7765a2e-6e6a-4516-94f0-ccc1cbf2a1ab\",\"webcompat-reporter@mozilla.org\":\"cd10bc1d-c45e-4b10-813c-286400722af1\",\"webcompat@mozilla.org\":\"9a975947-5868-4f58-a441-497d5d15b6c2\",\"default-theme@mozilla.org\":\"88ae6698-4e69-4620-9fa4-9d4a9e6efd56\",\"google@search.mozilla.org\":\"216aa559-4e49-4256-8efc-3c681f82db35\",\"amazondotcom@search.mozilla.org\":\"22c182ba-caf2-44a8-a684-2ac9ce91e365\",\"wikipedia@search.mozilla.org\":\"4e8244e2-a074-4664-8fa4-2c3d06ec1f4a\",\"bing@search.mozilla.org\":\"d8a697b4-d0a3-42ae-bfd4-6b43e72723ac\",\"ddg@search.mozilla.org\":\"7d5bae69-bed9-4fc4-92ef-456b2a505ee9\"}");
user_pref("idle.lastDailyNotification", 1610106186);
user_pref("media.gmp-manager.buildID", "20210106181555");
user_pref("media.gmp-manager.lastCheck", 1610106150);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1609891972);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1610106189);
user_pref("security.remote_settings.intermediates.checked", 1610106189);
user_pref("services.blocklist.addons-mlbf.checked", 1610106189);
user_pref("services.blocklist.gfx.checked", 1610106189);
user_pref("services.blocklist.pinning.checked", 1610106189);
user_pref("services.blocklist.plugins.checked", 1610106189);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1610092712207\"");
user_pref("services.settings.last_update_seconds", 1610106189);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1610106189);
user_pref("services.settings.main.cfr-fxa.last_check", 1610106189);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1610106189);
user_pref("services.settings.main.hijack-blocklists.last_check", 1610106189);
user_pref("services.settings.main.language-dictionaries.last_check", 1610106189);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1610106189);
user_pref("services.settings.main.public-suffix-list.last_check", 1610106189);
user_pref("services.settings.main.search-config.last_check", 1610106189);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1610106189);
user_pref("services.settings.main.sites-classification.last_check", 1610106189);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1610106189);
user_pref("services.settings.main.whats-new-panel.last_check", 1610106189);
user_pref("services.settings.security.onecrl.checked", 1610106189);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1609891971);
user_pref("toolkit.startup.last_success", 1610106423);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210106181555");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
