// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1609857733);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1609857731);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1609857715);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1609857853);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1609857764);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 6223);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1609857706);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f61ddbca-b83e-46e6-ab3c-0da236019570}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1609857715");
user_pref("browser.slowStartup.averageTime", 8320);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20201222151322");
user_pref("browser.startup.homepage_override.mstone", "78.6.0");
user_pref("browser.startup.lastColdStartupCheck", 1609857708);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.iniFile.exists.appversion", "78.6.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "454fec3b6385495e928d61f4cb11452c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.6.0");
user_pref("extensions.lastPlatformVersion", "78.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e3365f90-abc8-4ffb-a483-7c535758c089\",\"formautofill@mozilla.org\":\"232c3457-7c5b-4dba-aa44-3520fa860780\",\"screenshots@mozilla.org\":\"316e439a-b819-4258-80d3-425f1b63a0ad\",\"webcompat-reporter@mozilla.org\":\"2962cb76-de9c-4210-80f5-1dbaa6aa7c17\",\"webcompat@mozilla.org\":\"11ef9ba0-e9af-47ed-989b-2b54942b3d45\",\"default-theme@mozilla.org\":\"428f6ec5-9786-49bf-853f-261bafb82fb4\",\"google@search.mozilla.org\":\"6624e855-dddc-4887-9be2-bd82ed336206\",\"amazondotcom@search.mozilla.org\":\"771fe3d1-990e-4f35-9d6b-89603987323f\",\"wikipedia@search.mozilla.org\":\"a47c5e1a-e85d-4749-8f17-d537bee4613d\",\"bing@search.mozilla.org\":\"ad872225-57ce-4291-b47e-7fa63c035ca9\",\"ddg@search.mozilla.org\":\"34555fa1-6fa2-40fc-a4ea-06a54c77a7ba\"}");
user_pref("media.gmp-manager.buildID", "20201222151322");
user_pref("media.gmp-manager.lastCheck", 1609857729);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.intermediates.checked", 1609857728);
user_pref("services.blocklist.addons-mlbf.checked", 1609857728);
user_pref("services.blocklist.gfx.checked", 1609857728);
user_pref("services.blocklist.pinning.checked", 1609857728);
user_pref("services.blocklist.plugins.checked", 1609857728);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_update_seconds", 1609857728);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1609857728);
user_pref("services.settings.main.cfr-fxa.last_check", 1609857728);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1609857728);
user_pref("services.settings.main.hijack-blocklists.last_check", 1609857728);
user_pref("services.settings.main.language-dictionaries.last_check", 1609857728);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1609857728);
user_pref("services.settings.main.public-suffix-list.last_check", 1609857728);
user_pref("services.settings.main.search-config.last_check", 1609857728);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1609857728);
user_pref("services.settings.main.sites-classification.last_check", 1609857728);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1609857728);
user_pref("services.settings.main.whats-new-panel.last_check", 1609857728);
user_pref("services.settings.security.onecrl.checked", 1609857728);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1609857700);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20201222151322");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
