#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

colors() {
	local fgc bgc vals seq0

	printf "Color escapes are %s\n" '\e[${value};...;${value}m'
	printf "Values 30..37 are \e[33mforeground colors\e[m\n"
	printf "Values 40..47 are \e[43mbackground colors\e[m\n"
	printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

	# foreground colors
	for fgc in {30..37}; do
		# background colors
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black

			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}

			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
		done
		echo; echo
	done
}

[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

# Change the window title of X terminals
case ${TERM} in
	xterm*|rxvt*|Eterm*|aterm|kterm|gnome*|interix|konsole*)
		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
		;;
	screen*)
		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
		;;
esac

use_color=true

# Set colorful PS1 only on colorful terminals.
# dircolors --print-database uses its own built-in database
# instead of using /etc/DIR_COLORS.  Try to use the external file
# first to take advantage of user additions.  Use internal bash
# globbing instead of external grep binary.
safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM
match_lhs=""
[[ -f ~/.dir_colors   ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
[[ -f /etc/DIR_COLORS ]] && match_lhs="${match_lhs}$(</etc/DIR_COLORS)"
[[ -z ${match_lhs}    ]] \
	&& type -P dircolors >/dev/null \
	&& match_lhs=$(dircolors --print-database)
[[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] && use_color=true

if ${use_color} ; then
	# Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
	if type -P dircolors >/dev/null ; then
		if [[ -f ~/.dir_colors ]] ; then
			eval $(dircolors -b ~/.dir_colors)
		elif [[ -f /etc/DIR_COLORS ]] ; then
			eval $(dircolors -b /etc/DIR_COLORS)
		fi
	fi

	if [[ ${EUID} == 0 ]] ; then
		PS1='\[\033[01;31m\][\h\[\033[01;36m\] \W\[\033[01;31m\]]\$\[\033[00m\] '
	else
		PS1='\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] '
	fi

	alias ls='ls --color=auto'
	alias grep='grep --colour=auto'
	alias egrep='egrep --colour=auto'
	alias fgrep='fgrep --colour=auto'
else
	if [[ ${EUID} == 0 ]] ; then
		# show root@ when we don't have colors
		PS1='\u@\h \W \$ '
	else
		PS1='\u@\h \w \$ '
	fi
fi

unset use_color safe_term match_lhs sh

#alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less

xhost +local:root > /dev/null 2>&1

complete -cf sudo

# Bash won't get SIGWINCH if another process is in the foreground.
# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
# http://cnswww.cns.cwru.edu/~chet/bash/FAQ (E11)
shopt -s checkwinsize

shopt -s expand_aliases

# export QT_SELECT=4

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

#
# # ex - archive extractor
# # usage: ex <file>
extract ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


# My personal shortcuts 
#alias u='yay -Syu --noconfirm; cd /home/jonathan/sxmo-build; git pull https://git.sr.ht/~mil/sxmo-build/; cd ~'
alias uu='echo 282634 | sudo -S ~/sxmo-alarm/sxmo-alarm --force' 
alias u='yay -Syu --noconfirm' 
alias call='cd /home/jonathan/sxmo-build; ./sxmo_build_all.sh'
#alias cdwm='cp /home/jonathan/Documents/phone/configs/config.h /home/jonathan/sxmo-build/build-sxmo-dev/sxmo-dwm/config.h; cd /home/jonathan/sxmo-build/build-sxmo-dev/sxmo-dwm; sudo make install'
alias cdwm='echo 282634 | sudo -S cp /home/jonathan/Documents/phone/configs/config.h /home/jonathan/build-sxmo-dev/sxmo-dwm/config.h; cd /home/jonathan/build-sxmo-dev/sxmo-dwm; sudo make install'
alias srb='source ~/.bashrc'
alias in='yay -S'
alias pr='yay -Rsn'
alias sound='alsamixer'
alias bright='xrandr --output LVDS-1 --brightness'
alias sr='yay -Ss'
alias wifioff='nmcli radio wifi off'
alias wifion='nmcli radio wifi on'
#alias pdf2jpg='python3 /home/jonathan/Documents/myscripts/python-scripts/pdf2jpg.py'
alias pdf2jpg='sh /home/jonathan/Documents/myscripts/bash-scripts/pdf2jpg.sh'
alias gaa='git add --all'
alias gcm='git commit -m'
alias gac='git add --all && git commit -m'
alias gacp='sh ~/Documents/phone/bash-scripts/git-add-commit-push-main.sh'
alias gacpm='sh /home/jonathan/Documents/phone/bash-scripts/git-add-commit-push-main.sh'
alias gacpa='sh /home/jonathan/Documents/myscripts/bash-scripts/git-add-commit-push-assets.sh'
alias gpm='git push -u origin master'
alias gpa='git push -u origin assets'
alias gpc='git push -u origin calendar'
alias gromit-mpx='/home/jonathan/gromit-mpx-1.3.1/build/gromit-mpx'
alias cl='sudo pacman -Scc; rm -rf ~/.cache/*; sudo pacman -R $(pacman -Qdtq)'
alias gpmn='git push -u origin main'
alias cpcn='sh ~/Documents/phone/bash-scripts/cp-configs-startups.sh'
alias gcal='python /home/jonathan/gencal/calculators/gen_cal_v2/gen_cal_v2.py'
alias r='ranger'
alias m='featherpad'
alias ll='exa'
alias mc='micro'
alias n='nano'
alias gacpams='sh /home/jonathan/Documents/phone/bash-scripts/git-add-commit-push-assets-main.sh'
alias cleanzip='unzip "*.zip" && rm *.zip'
alias xl2jpg='sh /home/jonathan/Documents/laptop/myscripts/bash-scripts/xl2jpg.sh'
alias mb='featherpad ~/Documents/phone/configs/bashrc && cp ~/Documents/phone/configs/bashrc ~/.bashrc && source ~/.bashrc'
alias mcb='micro ~/Documents/phone/configs/bashrc && cp ~/Documents/phone/configs/bashrc ~/.bashrc && source ~/.bashrc'
alias rb='sudo reboot'
alias po='sudo poweroff'
alias mcc='micro ~/Documents/phone/configs/config.h'
alias smc='echo 282634 | sudo -S micro config.h'
alias mr='featherpad ~/Documents/phone/configs/rc.conf && cp ~/Documents/phone/configs/rc.conf ~/.config/ranger/rc.conf'
alias smci='echo 282634 | sudo -S make clean install'
alias ta='transmission-remote -w "/home/jonathan/Downloads/Movies" -a'
alias smi='echo 282634 | sudo -S make; echo 282634 | sudo -S make install'
alias td='transmission-daemon'
alias ts='torpar -t 4 -q'
alias tap='transmission-remote -w "/mnt/sdcard/.h" -a'
alias cast='echo 282634 | sudo -S systemctl start ums@jonathan.service'
alias stopcast='echo 282634 | sudo -S systemctl stop ums@jonathan.service'
alias tra='transmission-remote -t all -r'
alias smb='echo 282634 | sudo -S systemctl start smb.service; sudo systemctl start nmb.service'
alias smbstop='echo 282634 | sudo -S systemctl stop smb.service; sudo systemctl stop nmb.service'
alias tsa='transmission-remote -t all -s'
alias tsta='transmission-remote -t all -S'
alias tl='transmission-remote -l'
alias tra='transmission-remote -t all -r'
alias gdrive='rclone mount depedgdrive:/ /mnt/sdcard/GDrive &' 
alias la='ls -la'
alias usb='echo 282634 | sudo -S mount /dev/sda /home/jonathan/usb'
alias cdh='cd ~'
alias usbout='echo 282634 | sudo -S umount /dev/sda'
alias rx='echo 282634 | sudo -S systemctl restart display-manager'
alias upl='cd .. && ls'
alias bat='cat /sys/class/power_supply/axp20x-battery/capacity'

alias wr='sh /home/jonathan/Documents/phone/bash-scripts/watch-run.sh'

alias sshphone='ssh -p 8022 192.168.1.248'

alias sshl='ssh jonathan@192.168.1.249'

alias vnc='x11vnc -display :0 -usepw'

alias lower='/home/jonathan/Documents/laptop/myscripts/common-scripts/make-lowercase.sh'

export EDITOR=micro
export VISUAL=featherpad
shopt -s extglob

export PATH=/mnt/sdcard/Documents/phone/bin:/home/jonathan/Documents/phone/bash-scripts:/mnt/sdcard/Documents/laptop/scripts/bash-scripts:go/bin:/home/jonathan/.local/bin:$PATH
export TERM=xterm
export SSHPASS=bacolod1987
export TERMINFO=/bin/sh

up(){
  local d=""
  limit=$1
  for ((i=1 ; i <= limit ; i++))
    do
      d=$d/..
    done
  d=$(echo $d | sed 's/^\///')
  if [ -z "$d" ]; then
    d=..
  fi
  cd $d
}

cdl(){
  cd $1
  ls
}

function trt { transmission-remote -t $1 -r;}

function zipsend { zip -r $1 * && telegram-send -f $1; }
